put_user:
    path: v1/user
    controller: App\Controller\UserController::put
    methods: PUT

put_movie:
    path: v1/movie
    controller: App\Controller\MovieController::put
    methods: PUT

put_user_movie:
    path: v1/user/{idUser}/movie/{idMovie}
    controller: App\Controller\UserMovieController::put
    methods: PUT

delete_user_movie:
    path: v1/user/{idUser}/movie/{idMovie}
    controller: App\Controller\UserMovieController::delete
    methods: DELETE

get_user_movie:
    path: v1/user/{idUser}/movies
    controller: App\Controller\UserMovieController::getMovies
    methods: GET

get_movie_user:
    path: v1/movie/{idMovie}/users
    controller: App\Controller\UserMovieController::getUsers
    methods: GET

get_rank:
    path: v1/rank/movie
    controller: App\Controller\RankController::getMovie
    methods: GET