fos_rest:
    routing_loader:
      default_format: json
    view:
        view_response_listener:  true
    format_listener:
        rules:
            - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: html, prefer_extension: true }
    service:
      view_handler:         fos_rest.view_handler.default
    versioning:
      enabled: true